name = "CAP"
uuid = "d64df2ee-d2bb-46f4-8cbc-f03bb858f8cb"
authors = [
	"Sebastian Gutsche <gutsche@mathematik.uni-siegen.de>",
	"Sebastian Posur <sebastian.posur@uni-muenster.de>",
	"Øystein Skartsæterhagen <oysteini@math.ntnu.no>",
	"Fabian Zickgraf <fabian.zickgraf@uni-siegen.de>",
]
version = "0.1.0"

[compat]
julia = "1.8"
